### get all clients
GET http://localhost:3000/api/productos

### get one client
GET http://localhost:3000/api/productos/66902e647185119674495890


### create client
POST http://localhost:3000/api/productos/
Content-Type: application/json

{
    "nombre": "producto 10",
    "descripcion": "descripcion 10",
    "fechaAlta": "2023-09-01",
    "stock": 10,
    "precioVenta": 100,
    "modelo": "66903783b38f02b95917f0da"
}


### put client
PUT http://localhost:3000/api/productos/66900479772a039a334a94a1
Content-Type: application/json

{
    "nombreModelo": "modelo 1 cambio",
    "descripcion": "descripcion 1 cambio",
    "productos": []
   

}


### patch client
PATCH http://localhost:3000/api/productos/66900479772a039a334a94a1
Content-Type: application/json

{
    "productos": []
}


### delete client
DELETE http://localhost:3000/api/productos/66900479772a039a334a94a1