### get all clients
GET http://localhost:3000/api/subastas

### get one client
GET http://localhost:3000/api/subastas/xxxxxxxxxxxxxxxxxxx


### create client
POST http://localhost:3000/api/subastas/
Content-Type: application/json

{
    "fechaAlta": "2023-09-01",
    "fechahora": "descripcion 25",
    "precio_base_entrada": 10,
    "precio_cierre": 100,
    "producto": "66a25e9b26cc7f88926de44e",
    "usuarioCreador": "66a25ede26cc7f88926de44f",
    "usuarioGanador": "66a28ee01dbd5c9e5aece75b" 
}



### put client
PUT http://localhost:3000/api/subastas/xxxxxxxxxxxxxxxx
Content-Type: application/json

{
    "nombreUsuario": "usuario 1 cambio",
    "descripcion": "descripcion 1 cambio",
    "usuarios": []
    "productos": []
   

}


### patch client
PATCH http://localhost:3000/api/subastas/xxxxxxxxxxxxxxxxxx
Content-Type: application/json

{
    "usuarios": []
}


### delete client
DELETE http://localhost:3000/api/subastas/xxxxxxxxxxxxxxxxxxxx