### obtener todos los usuarios
GET http://localhost:3000/api/usuarios


### obtener un character
GET http://localhost:3000/api/usuarios/add641ca-fee4-4244-9157-73522eeb71dd

### crear un nuevo character
POST http://localhost:3000/api/usuarios/
Content-Type: application/json
{
    "fechaAlta": "2021-10-10",
    "fechaHora": "2021-10-10",
    "precioBaseEntrada": 1000,
    "precioCierre": 5000, 
}
### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/usuarios/0d159c3c-39e7-4980-b85e-634b1dfb44d1
Content-Type: application/json

{
  "precioBaseEntrada": 2000,
  "precioCierre": 6000,
}

### borrar un character
DELETE http://localhost:3000/api/usuarios/b66313da-6bf2-45ba-afdb-5cf3a9e06017