### obtener todos los usuarios
GET http://localhost:3000/api/usuarios


### obtener un character
GET http://localhost:3000/api/usuarios/add641ca-fee4-4244-9157-73522eeb71dd

### crear un nuevo character
POST http://localhost:3000/api/usuarios/
Content-Type: application/json

{
  "nombre": "Milton",
  "apellido": "Borsatito",
  "correo": "borsatomilton@gmail.com",
  "usuario": "1000ton",
  "contrasena": "123456",
  "direccion": "calle 53"
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/usuarios/0d159c3c-39e7-4980-b85e-634b1dfb44d1
Content-Type: application/json

{
  "nombre": "Camion",
  "apellido": "Vozzi",
  "correo": "pitutito@gmail.com",
  "usuario": "vozzi",
  "contrasena": "12345678",
  "direccion": "calle 54"
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/usuarios/0d159c3c-39e7-4980-b85e-634b1dfb44d1
Content-Type: application/json

{
  "nombre": "Ogro",
  "apellido": "Sastre"
}

### borrar un character
DELETE http://localhost:3000/api/usuarios/b66313da-6bf2-45ba-afdb-5cf3a9e06017