### get all compras
GET http://localhost:3000/api/compras

### get one compra
GET http://localhost:3000/api/pedidos/66902e647185119674495890

### create compra
POST http://localhost:3000/api/compras/
Content-Type: application/json

{
    "fechaCompra": "2023-11-01",
    "usuario": "66a41688d30644a3d53a88b4"
}

### delete pedido
DELETE http://localhost:3000/api/pedidos/66a41f22a5539ba11d0d8452