### get all tarjetas
GET http://localhost:3000/api/tarjetas 

### get one tarjeta
GET http://localhost:3000/api/tarjetas/66a28b7d10af30a819063177

### create tarjeta
POST http://localhost:3000/api/tarjetas
Content-Type: application/json

{
  "codSeguridad": 123,
  "fechaVencimiento": "2022-12-12 ",
  "usuario": "66a26a56c2d60a2b531e553b"
}


### put tarjeta
PUT http://localhost:3000/api/tarjetas/66a28b7d10af30a819063177
Content-Type: application/json

{
  "codSeguridad": 456
}

### delete tarjeta
DELETE http://localhost:3000/api/tarjetas/66a28b7d10af30a819063177