### get all pedidos
GET http://localhost:3000/api/pedidos

### get one pedido
GET http://localhost:3000/api/pedidos/66902e647185119674495890

### create pedido
POST http://localhost:3000/api/pedidos/

Content-Type: application/json

{
    "fecha": "2023-09-01",
    "cliente": "66903783b38f02b95917f0da",
    "productos": [
        {
            "producto": "66904310a5879a5c633b28bc",
            "cantidad": 2
        }
    ]
}

### put pedido
PUT http://localhost:3000/api/pedidos/66900479772a039a334a94a1
Content-Type: application/json

{
    "fecha": "2023-11-01",
    "cliente": "66903783b38f02b95917f0da",
    "productos": [
        {
            "producto": "66904310a5879a5c633b28bc",
            "cantidad": 4
        }
    ]
}

### patch pedido
PATCH http://localhost:3000/api/pedidos/66900479772a039a334a94a1

Content-Type: application/json

{
    "productos": [
        {
            "producto": "66904310a5879a5c633b28bc",
            "cantidad": 4
        }
    ]
}

### delete pedido
DELETE http://localhost:3000/api/pedidos/66900479772a039a334a94a1